spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authserver?serverTimezone=UTC
    username: shannon
    password: hung0602
    initialization-mode: always
    data:
        - classpath:/db/dev/data.sql
  jpa:
    # uncomment the below lines to view sql output in console
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate.ddl-auto: create-drop

# Server port is arbitrary
server:
  port: 23456
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

